import "./globals.css";
import Menu from "../components/Menu/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="bg-white text-slate-900 antialiased light">
      <body className="min-h-full flex flex-col">
        <header className="bg-slate-900 text-slate-50">
          <Menu />
        </header>
        <main className="flex-1 p-4 min-h-[calc(100vh-7rem)]">
          {children}
        </main>
        <footer className="bg-slate-900 text-slate-50 p-4 backdrop:blur-sm bottom-0 w-full ">
          <p>&copy; 2023 My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
